# -*- coding: utf-8 -*-
"""Desafios

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D_dmfy71c_RwJixC9jmu28C2yVqTmycY

## Aula 2: Análise exploratória dos dados

Para os desafios dessa aula, vamos utilizar a mesma base de dados que estamos utilizando para o desenvolvimento do nosso projeto. Sendo assim, na célula abaixo vamos realizar a importação dessa base de dados e aplicar as transformações já realizadas até o momento da aula 2.
"""

import pandas as pd

# importando a base de dados
url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/base-de-dados/aluguel.csv'
dados = pd.read_csv(url, sep=';')

imoveis_comerciais = ['Conjunto Comercial/Sala',
                      'Prédio Inteiro', 'Loja/Salão',
                      'Galpão/Depósito/Armazém',
                      'Casa Comercial', 'Terreno Padrão',
                      'Loja Shopping/ Ct Comercial',
                      'Box/Garagem', 'Chácara',
                      'Loteamento/Condomínio', 'Sítio',
                      'Pousada/Chalé', 'Hotel', 'Indústria']

# removendo imóveis comerciais
df = dados.query('@imoveis_comerciais not in Tipo')

# selecionando apenas imóveis do tipo apartamento
df = df.query('Tipo == "Apartamento"')

# visualizando a base de dados
df.head()

"""### Desafio 1
Calcular a média de quartos por apartamento
"""

media_quartos = df.groupby("Tipo")["Quartos"].mean()
media_quartos

"""### Desafio 2
Conferir quantos bairros únicos existem na nossa base de dados
"""

bairro_unicos = df.Bairro.nunique()
bairro_unicos

"""### Desafio 3
Analisar quais bairros possuem a média de valor de aluguel mais elevadas
"""

bairro_media = df.groupby("Bairro")["Valor"].mean().sort_values()
bairro_media

"""### Desafio 4
Criar um gráfico de barras verticais que apresente os 5 bairros com a média de valor de aluguel mais elevadas
"""

bairro_media_alta = df.groupby("Bairro")["Valor"].mean().sort_values()
melhores = bairro_media_alta.tail()

melhores.plot(x='Bairro', y='Valor', kind='bar', color="purple")

"""## Aula 3

Importe novamente o arquivo [**alunos.csv**](https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv) para realizar os desafios abaixo.
"""

# Importando novamente os dados
import pandas as pd
url = "https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv"
alunos = pd.read_csv(url)
alunos

"""### Desafio 1
Verifique se a base de dados possui dados nulos e caso tenha, realize o tratamento desses dados nulos
"""

alunos.isnull().sum()

alunos = alunos.fillna(0)

alunos.isnull().sum()
alunos

"""### Desafio 2
Os alunos "Alice" e "Carlos", não fazem mais parte da turma. Sendo assim, remova-os da base de dados
"""

alunos.Nome.unique()

alunos_que_sairam = ["Alice", "Carlos"]

dados = alunos.query("@alunos_que_sairam not in Nome")
dados

"""### Desafio 3
Aplique um filtro que selecione apenas os alunos que foram aprovados
"""

alunos_aprovados = dados.query("Aprovado == True")
alunos_aprovados

alunos_reprovados = dados.query("Aprovado == False")
alunos_reprovados

"""### Desafio 4
Salve o DataFrame que possui apenas os alunos aprovados em um arquivo csv chamado "alunos_aprovados.csv"
"""

alunos_aprovados.to_csv("Alunos Aprovados.csv")

pd.read_csv("Alunos Aprovados.csv")

"""### **Extra**
Ao conferir as notas dos alunos aprovados, notamos que algumas notas estavam incorretas. As alunas que tiraram nota 7.0, na verdade tinham um ponto extra que não foi contabilizado. Sendo assim, substitua as notas 7.0 da base de dados por 8.0. **Dica**: pesquise pelo método **replace**
"""

dados["Notas"] = dados["Notas"].replace(7, 8) # Primeiro pegue a coluna que quer dps atribua valores que estao e quais seriam, como no exemplo: o "7" virou "8"
dados





"""## Aula 4

Importe novamente o arquivo [**alunos.csv**](https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv) para realizar os desafios abaixo.
"""

# Importando novamente os dados
import pandas as pd

uri = "https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv"
dados = pd.read_csv(uri)
dados.head()

"""### Desafio 1
Os alunos participaram de uma atividade extracurricular e ganharam pontos extras. Esses pontos extras correspondem a 40% da nota atual de cada um deles. Com base nisso, crie uma coluna chamada "Pontos_extras" que contenha os pontos extras de cada aluno, ou seja, 40% da nota atual deles
"""

dados["Pontos_extras"] = dados['Notas'].apply(lambda x: x*0.4)
dados.head()

"""### Desafio 2
Crie mais uma coluna, chamada "Notas_finais" que possua as notas de cada aluno somada com os pontos extras
"""

dados["Notas_Finais"] = dados["Notas"] + dados["Pontos_extras"]
dados.head()

"""### Desafio 3
Como os alunos ganharam pontos extras, alguns que não tinham sido aprovados antes podem ter sido aprovados agora. Com base nisso, crie uma coluna chamada "Aprovado_final" com os seguintes valores:

* True: caso o aluno esteja aprovado (nota final deve ser maior ou igual a 6);
* False: caso o aluno esteja reprovado (nota final deve ser menor que 6).

"""



dados["Aprovados_final"] = dados["Notas_Finais"].apply(lambda x: "True" if x >= 6   else  x < 6)
dados

"""### Desafio 4
Faça uma seleção e verifique quais alunos não tinham sido aprovados anteriormente, mas foram aprovados após a soma dos pontos extras
"""

dados.query("Aprovado == False & Aprovados_final == True")
dados

